import { 
  faHomeAlt, 
  faArrowLeft,
  faMapMarkerAlt,
  faPlusCircle,
  faPlus,
  faEllipsisVertical,
  faSpinner,
  faSearch,
  faTrash,
  faWind,
  faTint,
  faSun,
  faMoon,
 } from "@fortawesome/free-solid-svg-icons";

export default {
  home: faHomeAlt,
  arrowLeft: faArrowLeft,
  mapMarkerAlt: faMapMarkerAlt,
  plusCircle: faPlusCircle,
  plus: faPlus,
  elipsisVertical: faEllipsisVertical,
  spinner: faSpinner,
  search: faSearch,
  trash: faTrash,
  wind: faWind,
  tint: faTint,
  sun: faSun,
  moon: faMoon,
};
